#!/bin/bash
# Car Bronze - Hostinger Deployment Command Reference
# Copy and paste these commands in order

echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║                 Car Bronze - Hostinger Deployment Commands                ║"
echo "║                          Copy & Paste in Order                               ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"

echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "STEP 1: PREPARE LOCALLY (Do this first!)"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "# Navigate to your project"
echo "cd c:\\Users\\ADV\\Downloads\\project"
echo ""
echo "# Clear cache and old builds"
echo "npm cache clean --force"
echo "rm -r node_modules .next package-lock.json"
echo ""
echo "# Install dependencies with Hostinger settings"
echo "npm install --legacy-peer-deps"
echo ""
echo "# TypeScript check (should pass)"
echo "npm run typecheck"
echo ""
echo "# Build for production"
echo "npm run build"
echo ""
echo "# Test the production build"
echo "npm start"
echo ""
echo "# Visit http://localhost:3000 in your browser"
echo "# Press Ctrl+C to stop the server"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "STEP 2: SETUP PRODUCTION ENVIRONMENT"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "# Create production environment file"
echo "cp .env.production.example .env.local"
echo ""
echo "# Edit .env.local with your actual values:"
echo "# - NEXT_PUBLIC_BASE_URL=https://yourdomain.com"
echo "# - DB_HOST, DB_USER, DB_PASSWORD, DB_NAME"
echo "# - SMTP_* variables for email"
echo "# - PAYPAL_* variables"
echo ""
echo "# Edit in VS Code:"
echo "code .env.local"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "STEP 3: UPLOAD TO HOSTINGER"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "OPTION A: Git Deployment (RECOMMENDED)"
echo "─────────────────────────────────────"
echo "# Push to GitHub"
echo "git add ."
echo "git commit -m 'Deploy to Hostinger - production ready'"
echo "git push origin main"
echo ""
echo "# Then in Hostinger Control Panel:"
echo "# 1. Go to Git"
echo "# 2. Connect repository"
echo "# 3. Set build command: npm run build"
echo "# 4. Click Deploy"
echo ""

echo "OPTION B: FTP Upload"
echo "────────────────────"
echo "# Clean up before zipping"
echo "rm -r node_modules .next .git"
echo ""
echo "# Create zip file"
echo "Compress-Archive -Path . -DestinationPath autofactscheck.zip"
echo ""
echo "# Upload via FTP to public_html"
echo "# Then extract on Hostinger"
echo ""

echo "OPTION C: SSH"
echo "─────────────"
echo "# SSH into server"
echo "ssh user@yourdomain.com"
echo ""
echo "# Navigate to project"
echo "cd public_html"
echo ""
echo "# Install dependencies"
echo "npm install --legacy-peer-deps"
echo ""
echo "# Build"
echo "npm run build"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "STEP 4: CONFIGURE HOSTINGER NODE.JS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "IN HOSTINGER CONTROL PANEL:"
echo "─────────────────────────────"
echo "1. Go to Node.js section"
echo "2. Click Create Application or Modify"
echo "3. Set these values:"
echo "   - Application Root: /public_html/"
echo "   - Node.js Version: 18.x or 20.x"
echo "   - Startup File: npm start"
echo "   - Node Environment: production"
echo "   - Port: (leave default)"
echo ""
echo "4. Add Environment Variables in Hostinger:"
echo "   - NEXT_PUBLIC_BASE_URL=https://yourdomain.com"
echo "   - NODE_ENV=production"
echo "   - DB_HOST, DB_USER, DB_PASSWORD, DB_NAME"
echo "   - SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD"
echo "   - NEXT_PUBLIC_PAYPAL_CLIENT_ID"
echo "   - (see .env.production.example for all variables)"
echo ""
echo "5. Click Deploy/Save"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "STEP 5: VERIFY DEPLOYMENT"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "# Check if site is live"
echo "curl https://yourdomain.com"
echo ""
echo "# Check specific pages"
echo "curl https://yourdomain.com/about-us"
echo "curl https://yourdomain.com/pricing"
echo "curl https://yourdomain.com/robots.txt"
echo "curl https://yourdomain.com/sitemap.xml"
echo ""
echo "# Check Hostinger logs:"
echo "# 1. Hostinger Control Panel → Node.js"
echo "# 2. Click View Logs"
echo "# 3. Check for errors"
echo ""
echo "# Verify in browser:"
echo "# 1. Visit https://yourdomain.com"
echo "# 2. Check all pages work"
echo "# 3. Check database (forms)"
echo "# 4. Check images load"
echo "# 5. Right-click → View Page Source (check meta tags)"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "QUICK TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "If you get Error 113:"
echo "  npm cache clean --force"
echo "  rm -r node_modules package-lock.json"
echo "  npm install --legacy-peer-deps --no-audit"
echo ""
echo "If app won't start:"
echo "  1. Check .env.local exists with values"
echo "  2. Check database credentials"
echo "  3. Check Hostinger logs for error messages"
echo "  4. Verify Node.js version is 18+"
echo ""
echo "If database connection fails:"
echo "  1. Verify DB_HOST is accessible from Hostinger"
echo "  2. Check DB_USER has proper permissions"
echo "  3. Verify database exists"
echo ""
echo "If site shows Error 404:"
echo "  1. Check application root path in Hostinger"
echo "  2. Verify .next folder exists"
echo "  3. Check startup command is correct"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION FILES"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Quick Reference:"
echo "  → README_DEPLOYMENT.md (5 min read)"
echo "  → HOSTINGER_QUICK_START.md (5 min read)"
echo ""
echo "Complete Guides:"
echo "  → HOSTINGER_DEPLOYMENT.md (20 min read - full details)"
echo "  → DEPLOYMENT_CHECKLIST.md (verification steps)"
echo "  → DEPLOYMENT_COMPLETE.md (summary of all changes)"
echo ""
echo "Navigation:"
echo "  → DOCS_INDEX.md (all guides in one place)"
echo ""
echo "Configuration:"
echo "  → .env.production.example (copy to .env.local)"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "✅ STATUS: PRODUCTION READY"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Your application is fully prepared for Hostinger deployment."
echo "Follow the steps above and you'll be live in 25-30 minutes!"
echo ""
echo "Good luck! 🚀"
echo ""
