export interface CountryEntry {
  code: string
  name: string
  countryCode: string // for flagcdn
  currency: string
  language: string
}

// Comprehensive country list (ISO A2). Primary/default language chosen conservatively.
// If you want different defaults for specific regions, tell me and I'll update.
export const countriesList: CountryEntry[] = [
  { code: 'AF', name: 'Afghanistan', countryCode: 'af', currency: 'AFN', language: 'ps' },
  { code: 'AL', name: 'Albania', countryCode: 'al', currency: 'ALL', language: 'sq' },
  { code: 'DZ', name: 'Algeria', countryCode: 'dz', currency: 'DZD', language: 'ar' },
  { code: 'AS', name: 'American Samoa', countryCode: 'as', currency: 'USD', language: 'en' },
  { code: 'AD', name: 'Andorra', countryCode: 'ad', currency: 'EUR', language: 'ca' },
  { code: 'AO', name: 'Angola', countryCode: 'ao', currency: 'AOA', language: 'pt' },
  { code: 'AG', name: 'Antigua & Barbuda', countryCode: 'ag', currency: 'XCD', language: 'en' },
  { code: 'AR', name: 'Argentina', countryCode: 'ar', currency: 'ARS', language: 'es' },
  { code: 'AM', name: 'Armenia', countryCode: 'am', currency: 'AMD', language: 'hy' },
  { code: 'AU', name: 'Australia', countryCode: 'au', currency: 'AUD', language: 'en' },
  { code: 'AT', name: 'Austria', countryCode: 'at', currency: 'EUR', language: 'de' },
  { code: 'AZ', name: 'Azerbaijan', countryCode: 'az', currency: 'AZN', language: 'az' },
  { code: 'BS', name: 'Bahamas', countryCode: 'bs', currency: 'BSD', language: 'en' },
  { code: 'BH', name: 'Bahrain', countryCode: 'bh', currency: 'BHD', language: 'ar' },
  { code: 'BD', name: 'Bangladesh', countryCode: 'bd', currency: 'BDT', language: 'bn' },
  { code: 'BB', name: 'Barbados', countryCode: 'bb', currency: 'BBD', language: 'en' },
  { code: 'BY', name: 'Belarus', countryCode: 'by', currency: 'BYN', language: 'be' },
  { code: 'BE', name: 'Belgium', countryCode: 'be', currency: 'EUR', language: 'nl' },
  { code: 'BZ', name: 'Belize', countryCode: 'bz', currency: 'BZD', language: 'en' },
  { code: 'BJ', name: 'Benin', countryCode: 'bj', currency: 'XOF', language: 'fr' },
  { code: 'BT', name: 'Bhutan', countryCode: 'bt', currency: 'BTN', language: 'dz' },
  { code: 'BO', name: 'Bolivia', countryCode: 'bo', currency: 'BOB', language: 'es' },
  { code: 'BA', name: 'Bosnia & Herzegovina', countryCode: 'ba', currency: 'BAM', language: 'bs' },
  { code: 'BW', name: 'Botswana', countryCode: 'bw', currency: 'BWP', language: 'en' },
  { code: 'BR', name: 'Brazil', countryCode: 'br', currency: 'BRL', language: 'pt' },
  { code: 'BN', name: 'Brunei', countryCode: 'bn', currency: 'BND', language: 'ms' },
  { code: 'BG', name: 'Bulgaria', countryCode: 'bg', currency: 'BGN', language: 'bg' },
  { code: 'BF', name: 'Burkina Faso', countryCode: 'bf', currency: 'XOF', language: 'fr' },
  { code: 'BI', name: 'Burundi', countryCode: 'bi', currency: 'BIF', language: 'fr' },
  { code: 'KH', name: 'Cambodia', countryCode: 'kh', currency: 'KHR', language: 'km' },
  { code: 'CM', name: 'Cameroon', countryCode: 'cm', currency: 'XAF', language: 'fr' },
  { code: 'CA', name: 'Canada', countryCode: 'ca', currency: 'CAD', language: 'en' },
  { code: 'CV', name: 'Cape Verde', countryCode: 'cv', currency: 'CVE', language: 'pt' },
  { code: 'CF', name: 'Central African Republic', countryCode: 'cf', currency: 'XAF', language: 'fr' },
  { code: 'TD', name: 'Chad', countryCode: 'td', currency: 'XAF', language: 'fr' },
  { code: 'CL', name: 'Chile', countryCode: 'cl', currency: 'CLP', language: 'es' },
  { code: 'CN', name: 'China', countryCode: 'cn', currency: 'CNY', language: 'zh' },
  { code: 'CO', name: 'Colombia', countryCode: 'co', currency: 'COP', language: 'es' },
  { code: 'KM', name: 'Comoros', countryCode: 'km', currency: 'KMF', language: 'ar' },
  { code: 'CG', name: 'Congo (Brazzaville)', countryCode: 'cg', currency: 'XAF', language: 'fr' },
  { code: 'CD', name: 'Congo (Kinshasa)', countryCode: 'cd', currency: 'CDF', language: 'fr' },
  { code: 'CR', name: 'Costa Rica', countryCode: 'cr', currency: 'CRC', language: 'es' },
  { code: 'CI', name: 'Côte d’Ivoire', countryCode: 'ci', currency: 'XOF', language: 'fr' },
  { code: 'HR', name: 'Croatia', countryCode: 'hr', currency: 'HRK', language: 'hr' },
  { code: 'CU', name: 'Cuba', countryCode: 'cu', currency: 'CUP', language: 'es' },
  { code: 'CY', name: 'Cyprus', countryCode: 'cy', currency: 'EUR', language: 'el' },
  { code: 'CZ', name: 'Czech Republic', countryCode: 'cz', currency: 'CZK', language: 'cs' },
  { code: 'DK', name: 'Denmark', countryCode: 'dk', currency: 'DKK', language: 'da' },
  { code: 'DJ', name: 'Djibouti', countryCode: 'dj', currency: 'DJF', language: 'fr' },
  { code: 'DM', name: 'Dominica', countryCode: 'dm', currency: 'XCD', language: 'en' },
  { code: 'DO', name: 'Dominican Republic', countryCode: 'do', currency: 'DOP', language: 'es' },
  { code: 'EC', name: 'Ecuador', countryCode: 'ec', currency: 'USD', language: 'es' },
  { code: 'EG', name: 'Egypt', countryCode: 'eg', currency: 'EGP', language: 'ar' },
  { code: 'SV', name: 'El Salvador', countryCode: 'sv', currency: 'USD', language: 'es' },
  { code: 'GQ', name: 'Equatorial Guinea', countryCode: 'gq', currency: 'XAF', language: 'es' },
  { code: 'ER', name: 'Eritrea', countryCode: 'er', currency: 'ERN', language: 'ti' },
  { code: 'EE', name: 'Estonia', countryCode: 'ee', currency: 'EUR', language: 'et' },
  { code: 'SZ', name: 'Eswatini', countryCode: 'sz', currency: 'SZL', language: 'en' },
  { code: 'ET', name: 'Ethiopia', countryCode: 'et', currency: 'ETB', language: 'am' },
  { code: 'FJ', name: 'Fiji', countryCode: 'fj', currency: 'FJD', language: 'en' },
  { code: 'FI', name: 'Finland', countryCode: 'fi', currency: 'EUR', language: 'fi' },
  { code: 'FR', name: 'France', countryCode: 'fr', currency: 'EUR', language: 'fr' },
  { code: 'GA', name: 'Gabon', countryCode: 'ga', currency: 'XAF', language: 'fr' },
  { code: 'GM', name: 'Gambia', countryCode: 'gm', currency: 'GMD', language: 'en' },
  { code: 'GE', name: 'Georgia', countryCode: 'ge', currency: 'GEL', language: 'ka' },
  { code: 'DE', name: 'Germany', countryCode: 'de', currency: 'EUR', language: 'de' },
  { code: 'GH', name: 'Ghana', countryCode: 'gh', currency: 'GHS', language: 'en' },
  { code: 'GR', name: 'Greece', countryCode: 'gr', currency: 'EUR', language: 'el' },
  { code: 'GD', name: 'Grenada', countryCode: 'gd', currency: 'XCD', language: 'en' },
  { code: 'GT', name: 'Guatemala', countryCode: 'gt', currency: 'GTQ', language: 'es' },
  { code: 'GN', name: 'Guinea', countryCode: 'gn', currency: 'GNF', language: 'fr' },
  { code: 'GW', name: 'Guinea-Bissau', countryCode: 'gw', currency: 'XOF', language: 'pt' },
  { code: 'GY', name: 'Guyana', countryCode: 'gy', currency: 'GYD', language: 'en' },
  { code: 'HT', name: 'Haiti', countryCode: 'ht', currency: 'HTG', language: 'fr' },
  { code: 'HN', name: 'Honduras', countryCode: 'hn', currency: 'HNL', language: 'es' },
  { code: 'HK', name: 'Hong Kong', countryCode: 'hk', currency: 'HKD', language: 'zh' },
  { code: 'HU', name: 'Hungary', countryCode: 'hu', currency: 'HUF', language: 'hu' },
  { code: 'IS', name: 'Iceland', countryCode: 'is', currency: 'ISK', language: 'is' },
  { code: 'IN', name: 'India', countryCode: 'in', currency: 'INR', language: 'en' },
  { code: 'ID', name: 'Indonesia', countryCode: 'id', currency: 'IDR', language: 'id' },
  { code: 'IR', name: 'Iran', countryCode: 'ir', currency: 'IRR', language: 'fa' },
  { code: 'IQ', name: 'Iraq', countryCode: 'iq', currency: 'IQD', language: 'ar' },
  { code: 'IE', name: 'Ireland', countryCode: 'ie', currency: 'EUR', language: 'en' },
  { code: 'IL', name: 'Israel', countryCode: 'il', currency: 'ILS', language: 'he' },
  { code: 'IT', name: 'Italy', countryCode: 'it', currency: 'EUR', language: 'it' },
  { code: 'JM', name: 'Jamaica', countryCode: 'jm', currency: 'JMD', language: 'en' },
  { code: 'JP', name: 'Japan', countryCode: 'jp', currency: 'JPY', language: 'ja' },
  { code: 'JO', name: 'Jordan', countryCode: 'jo', currency: 'JOD', language: 'ar' },
  { code: 'KZ', name: 'Kazakhstan', countryCode: 'kz', currency: 'KZT', language: 'kk' },
  { code: 'KE', name: 'Kenya', countryCode: 'ke', currency: 'KES', language: 'en' },
  { code: 'KI', name: 'Kiribati', countryCode: 'ki', currency: 'AUD', language: 'en' },
  { code: 'KP', name: 'North Korea', countryCode: 'kp', currency: 'KPW', language: 'ko' },
  { code: 'KR', name: 'South Korea', countryCode: 'kr', currency: 'KRW', language: 'ko' },
  { code: 'KW', name: 'Kuwait', countryCode: 'kw', currency: 'KWD', language: 'ar' },
  { code: 'KG', name: 'Kyrgyzstan', countryCode: 'kg', currency: 'KGS', language: 'ky' },
  { code: 'LA', name: 'Laos', countryCode: 'la', currency: 'LAK', language: 'lo' },
  { code: 'LV', name: 'Latvia', countryCode: 'lv', currency: 'EUR', language: 'lv' },
  { code: 'LB', name: 'Lebanon', countryCode: 'lb', currency: 'LBP', language: 'ar' },
  { code: 'LS', name: 'Lesotho', countryCode: 'ls', currency: 'LSL', language: 'en' },
  { code: 'LR', name: 'Liberia', countryCode: 'lr', currency: 'LRD', language: 'en' },
  { code: 'LY', name: 'Libya', countryCode: 'ly', currency: 'LYD', language: 'ar' },
  { code: 'LI', name: 'Liechtenstein', countryCode: 'li', currency: 'CHF', language: 'de' },
  { code: 'LT', name: 'Lithuania', countryCode: 'lt', currency: 'EUR', language: 'lt' },
  { code: 'LU', name: 'Luxembourg', countryCode: 'lu', currency: 'EUR', language: 'fr' },
  { code: 'MO', name: 'Macao', countryCode: 'mo', currency: 'MOP', language: 'zh' },
  { code: 'MK', name: 'North Macedonia', countryCode: 'mk', currency: 'MKD', language: 'mk' },
  { code: 'MG', name: 'Madagascar', countryCode: 'mg', currency: 'MGA', language: 'fr' },
  { code: 'MW', name: 'Malawi', countryCode: 'mw', currency: 'MWK', language: 'en' },
  { code: 'MY', name: 'Malaysia', countryCode: 'my', currency: 'MYR', language: 'ms' },
  { code: 'MV', name: 'Maldives', countryCode: 'mv', currency: 'MVR', language: 'dv' },
  { code: 'ML', name: 'Mali', countryCode: 'ml', currency: 'XOF', language: 'fr' },
  { code: 'MT', name: 'Malta', countryCode: 'mt', currency: 'EUR', language: 'mt' },
  { code: 'MH', name: 'Marshall Islands', countryCode: 'mh', currency: 'USD', language: 'en' },
  { code: 'MR', name: 'Mauritania', countryCode: 'mr', currency: 'MRU', language: 'ar' },
  { code: 'MU', name: 'Mauritius', countryCode: 'mu', currency: 'MUR', language: 'en' },
  { code: 'MX', name: 'Mexico', countryCode: 'mx', currency: 'MXN', language: 'es' },
  { code: 'FM', name: 'Micronesia', countryCode: 'fm', currency: 'USD', language: 'en' },
  { code: 'MD', name: 'Moldova', countryCode: 'md', currency: 'MDL', language: 'ro' },
  { code: 'MC', name: 'Monaco', countryCode: 'mc', currency: 'EUR', language: 'fr' },
  { code: 'MN', name: 'Mongolia', countryCode: 'mn', currency: 'MNT', language: 'mn' },
  { code: 'ME', name: 'Montenegro', countryCode: 'me', currency: 'EUR', language: 'sr' },
  { code: 'MA', name: 'Morocco', countryCode: 'ma', currency: 'MAD', language: 'ar' },
  { code: 'MZ', name: 'Mozambique', countryCode: 'mz', currency: 'MZN', language: 'pt' },
  { code: 'MM', name: 'Myanmar', countryCode: 'mm', currency: 'MMK', language: 'my' },
  { code: 'NA', name: 'Namibia', countryCode: 'na', currency: 'NAD', language: 'en' },
  { code: 'NR', name: 'Nauru', countryCode: 'nr', currency: 'AUD', language: 'en' },
  { code: 'NP', name: 'Nepal', countryCode: 'np', currency: 'NPR', language: 'ne' },
  { code: 'NL', name: 'Netherlands', countryCode: 'nl', currency: 'EUR', language: 'nl' },
  { code: 'NZ', name: 'New Zealand', countryCode: 'nz', currency: 'NZD', language: 'en' },
  { code: 'NI', name: 'Nicaragua', countryCode: 'ni', currency: 'NIO', language: 'es' },
  { code: 'NE', name: 'Niger', countryCode: 'ne', currency: 'XOF', language: 'fr' },
  { code: 'NG', name: 'Nigeria', countryCode: 'ng', currency: 'NGN', language: 'en' },
  { code: 'NO', name: 'Norway', countryCode: 'no', currency: 'NOK', language: 'no' },
  { code: 'OM', name: 'Oman', countryCode: 'om', currency: 'OMR', language: 'ar' },
  { code: 'PK', name: 'Pakistan', countryCode: 'pk', currency: 'PKR', language: 'ur' },
  { code: 'PW', name: 'Palau', countryCode: 'pw', currency: 'USD', language: 'en' },
  { code: 'PS', name: 'Palestine', countryCode: 'ps', currency: 'ILS', language: 'ar' },
  { code: 'PA', name: 'Panama', countryCode: 'pa', currency: 'PAB', language: 'es' },
  { code: 'PG', name: 'Papua New Guinea', countryCode: 'pg', currency: 'PGK', language: 'en' },
  { code: 'PY', name: 'Paraguay', countryCode: 'py', currency: 'PYG', language: 'es' },
  { code: 'PE', name: 'Peru', countryCode: 'pe', currency: 'PEN', language: 'es' },
  { code: 'PH', name: 'Philippines', countryCode: 'ph', currency: 'PHP', language: 'en' },
  { code: 'PL', name: 'Poland', countryCode: 'pl', currency: 'PLN', language: 'pl' },
  { code: 'PT', name: 'Portugal', countryCode: 'pt', currency: 'EUR', language: 'pt' },
  { code: 'QA', name: 'Qatar', countryCode: 'qa', currency: 'QAR', language: 'ar' },
  { code: 'RO', name: 'Romania', countryCode: 'ro', currency: 'RON', language: 'ro' },
  { code: 'RU', name: 'Russia', countryCode: 'ru', currency: 'RUB', language: 'ru' },
  { code: 'RW', name: 'Rwanda', countryCode: 'rw', currency: 'RWF', language: 'rw' },
  { code: 'KN', name: 'Saint Kitts & Nevis', countryCode: 'kn', currency: 'XCD', language: 'en' },
  { code: 'LC', name: 'Saint Lucia', countryCode: 'lc', currency: 'XCD', language: 'en' },
  { code: 'VC', name: 'Saint Vincent & the Grenadines', countryCode: 'vc', currency: 'XCD', language: 'en' },
  { code: 'WS', name: 'Samoa', countryCode: 'ws', currency: 'WST', language: 'sm' },
  { code: 'SM', name: 'San Marino', countryCode: 'sm', currency: 'EUR', language: 'it' },
  { code: 'ST', name: 'Sao Tome & Principe', countryCode: 'st', currency: 'STN', language: 'pt' },
  { code: 'SA', name: 'Saudi Arabia', countryCode: 'sa', currency: 'SAR', language: 'ar' },
  { code: 'SN', name: 'Senegal', countryCode: 'sn', currency: 'XOF', language: 'fr' },
  { code: 'RS', name: 'Serbia', countryCode: 'rs', currency: 'RSD', language: 'sr' },
  { code: 'SC', name: 'Seychelles', countryCode: 'sc', currency: 'SCR', language: 'fr' },
  { code: 'SL', name: 'Sierra Leone', countryCode: 'sl', currency: 'SLL', language: 'en' },
  { code: 'SG', name: 'Singapore', countryCode: 'sg', currency: 'SGD', language: 'en' },
  { code: 'SK', name: 'Slovakia', countryCode: 'sk', currency: 'EUR', language: 'sk' },
  { code: 'SI', name: 'Slovenia', countryCode: 'si', currency: 'EUR', language: 'sl' },
  { code: 'SB', name: 'Solomon Islands', countryCode: 'sb', currency: 'SBD', language: 'en' },
  { code: 'SO', name: 'Somalia', countryCode: 'so', currency: 'SOS', language: 'so' },
  { code: 'ZA', name: 'South Africa', countryCode: 'za', currency: 'ZAR', language: 'en' },
  { code: 'ES', name: 'Spain', countryCode: 'es', currency: 'EUR', language: 'es' },
  { code: 'LK', name: 'Sri Lanka', countryCode: 'lk', currency: 'LKR', language: 'si' },
  { code: 'SD', name: 'Sudan', countryCode: 'sd', currency: 'SDG', language: 'ar' },
  { code: 'SR', name: 'Suriname', countryCode: 'sr', currency: 'SRD', language: 'nl' },
  { code: 'SE', name: 'Sweden', countryCode: 'se', currency: 'SEK', language: 'sv' },
  { code: 'CH', name: 'Switzerland', countryCode: 'ch', currency: 'CHF', language: 'de' },
  { code: 'SY', name: 'Syria', countryCode: 'sy', currency: 'SYP', language: 'ar' },
  { code: 'TW', name: 'Taiwan', countryCode: 'tw', currency: 'TWD', language: 'zh' },
  { code: 'TJ', name: 'Tajikistan', countryCode: 'tj', currency: 'TJS', language: 'tg' },
  { code: 'TZ', name: 'Tanzania', countryCode: 'tz', currency: 'TZS', language: 'sw' },
  { code: 'TH', name: 'Thailand', countryCode: 'th', currency: 'THB', language: 'th' },
  { code: 'TL', name: 'Timor-Leste', countryCode: 'tl', currency: 'USD', language: 'pt' },
  { code: 'TG', name: 'Togo', countryCode: 'tg', currency: 'XOF', language: 'fr' },
  { code: 'TO', name: 'Tonga', countryCode: 'to', currency: 'TOP', language: 'to' },
  { code: 'TT', name: 'Trinidad & Tobago', countryCode: 'tt', currency: 'TTD', language: 'en' },
  { code: 'TN', name: 'Tunisia', countryCode: 'tn', currency: 'TND', language: 'ar' },
  { code: 'TR', name: 'Turkey', countryCode: 'tr', currency: 'TRY', language: 'tr' },
  { code: 'TM', name: 'Turkmenistan', countryCode: 'tm', currency: 'TMT', language: 'tk' },
  { code: 'UG', name: 'Uganda', countryCode: 'ug', currency: 'UGX', language: 'en' },
  { code: 'UA', name: 'Ukraine', countryCode: 'ua', currency: 'UAH', language: 'uk' },
  { code: 'AE', name: 'United Arab Emirates', countryCode: 'ae', currency: 'AED', language: 'ar' },
  { code: 'GB', name: 'United Kingdom', countryCode: 'gb', currency: 'GBP', language: 'en' },
  { code: 'US', name: 'United States', countryCode: 'us', currency: 'USD', language: 'en' },
  { code: 'UY', name: 'Uruguay', countryCode: 'uy', currency: 'UYU', language: 'es' },
  { code: 'UZ', name: 'Uzbekistan', countryCode: 'uz', currency: 'UZS', language: 'uz' },
  { code: 'VU', name: 'Vanuatu', countryCode: 'vu', currency: 'VUV', language: 'bi' },
  { code: 'VA', name: 'Vatican City', countryCode: 'va', currency: 'EUR', language: 'it' },
  { code: 'VE', name: 'Venezuela', countryCode: 've', currency: 'VEF', language: 'es' },
  { code: 'VN', name: 'Vietnam', countryCode: 'vn', currency: 'VND', language: 'vi' },
  { code: 'YE', name: 'Yemen', countryCode: 'ye', currency: 'YER', language: 'ar' },
  { code: 'ZM', name: 'Zambia', countryCode: 'zm', currency: 'ZMW', language: 'en' },
  { code: 'ZW', name: 'Zimbabwe', countryCode: 'zw', currency: 'ZWL', language: 'en' },
]

export default countriesList
